export interface AppRegistryItem {
  key: string;
  title: string;
  category: 'operations' | 'admin_docs' | 'finance' | 'warehouse';
  icon: string; // Lucide icon name
  color: string;
  bgColor: string;
  adminRoute?: string;
  leaderRoute?: string;
  employeeRoute?: string;
  isCore?: boolean;
  badgeKey?: 'pendingRequests' | 'dueTasks' | 'pendingVault';
}

export const CORE_APP_KEYS = ['attendance', 'requests', 'tasks', 'feedbacks'] as const;

export const APP_CATEGORIES = [
  { id: 'operations', label: 'VẬN HÀNH & NHÂN SỰ' },
  { id: 'admin_docs', label: 'HÀNH CHÍNH & TÀI LIỆU' },
  { id: 'finance', label: 'TÀI CHÍNH & ĐÃI NGỘ' },
  { id: 'warehouse', label: 'KHO BÃI & TÀI SẢN' },
] as const;

export const APP_REGISTRY: Record<string, AppRegistryItem> = {
  // 4 Cốt lõi (Core)
  attendance: {
    key: 'attendance',
    title: 'Chấm công',
    category: 'operations',
    icon: 'Clock',
    color: '#0284C7',
    bgColor: '#E0F2FE',
    adminRoute: '/admin/attendance',
    leaderRoute: '/leader/schedule',
    employeeRoute: '/employee/attendance',
    isCore: true,
  },
  requests: {
    key: 'requests',
    title: 'Đơn từ',
    category: 'admin_docs',
    icon: 'SquareCheck',
    color: '#0D9488',
    bgColor: '#CCFBF1',
    adminRoute: '/leader/approvals',
    leaderRoute: '/leader/approvals',
    employeeRoute: '/employee/requests',
    badgeKey: 'pendingRequests',
    isCore: true,
  },
  tasks: {
    key: 'tasks',
    title: 'Công việc',
    category: 'admin_docs',
    icon: 'Briefcase',
    color: '#6366F1',
    bgColor: '#EDE9FE',
    adminRoute: '/admin/tasks',
    leaderRoute: '/leader/tasks',
    employeeRoute: '/employee/tasks',
    badgeKey: 'dueTasks',
    isCore: true,
  },
  feedbacks: {
    key: 'feedbacks',
    title: 'Góp ý',
    category: 'admin_docs',
    icon: 'MessageSquare',
    color: '#059669',
    bgColor: '#ECFDF5',
    adminRoute: '/admin/feedbacks',
    leaderRoute: '/admin/feedbacks',
    employeeRoute: '/employee/feedbacks',
    isCore: true,
  },

  // Vận hành & Nhân sự
  shifts: {
    key: 'shifts',
    title: 'Phân ca làm',
    category: 'operations',
    icon: 'Calendar',
    color: '#EA580C',
    bgColor: '#FFEDD5',
    adminRoute: '/leader/shift-management',
    leaderRoute: '/leader/shift-management',
    employeeRoute: '/employee/schedule',
  },
  shift_swaps: {
    key: 'shift_swaps',
    title: 'Đổi ca',
    category: 'operations',
    icon: 'ArrowRightLeft',
    color: '#9333EA',
    bgColor: '#F3E8FF',
    adminRoute: '/leader/shift-swaps',
    leaderRoute: '/leader/shift-swaps',
    employeeRoute: '/employee/shift-swaps',
  },
  timesheet: {
    key: 'timesheet',
    title: 'Bảng công',
    category: 'operations',
    icon: 'CalendarDays',
    color: '#0D9488',
    bgColor: '#CCFBF1',
    adminRoute: '/admin/timesheet',
    leaderRoute: '/leader/timesheet',
    employeeRoute: '/employee/timesheet',
  },
  employees: {
    key: 'employees',
    title: 'Hồ sơ nhân sự',
    category: 'operations',
    icon: 'Users',
    color: '#7C3AED',
    bgColor: '#F3E8FF',
    adminRoute: '/admin/employees',
    leaderRoute: '/admin/employees',
    employeeRoute: '/employee/contacts',
  },
  departments: {
    key: 'departments',
    title: 'Cơ cấu PB',
    category: 'operations',
    icon: 'Building2',
    color: '#475569',
    bgColor: '#F1F5F9',
    adminRoute: '/admin/departments',
    leaderRoute: '/admin/departments',
    employeeRoute: '/employee/departments',
  },
  leaders: {
    key: 'leaders',
    title: 'Gán Leader',
    category: 'operations',
    icon: 'UserCheck',
    color: '#4F46E5',
    bgColor: '#EEF2FF',
    adminRoute: '/admin/leaders',
    leaderRoute: '/admin/leaders',
    employeeRoute: '/employee/leaders',
  },
  locations: {
    key: 'locations',
    title: 'Điểm chấm công',
    category: 'operations',
    icon: 'MapPin',
    color: '#E11D48',
    bgColor: '#FFE4E6',
    adminRoute: '/admin/attendance-locations',
    leaderRoute: '/admin/attendance-locations',
    employeeRoute: '/employee/attendance',
  },
  ot_live: {
    key: 'ot_live',
    title: 'Duyệt OT Live',
    category: 'operations',
    icon: 'Tv',
    color: '#E11D48',
    bgColor: '#FFE4E6',
    adminRoute: '/leader/ot-report-approvals',
    leaderRoute: '/leader/ot-report-approvals',
    employeeRoute: '/employee/ot-reports',
  },

  // Hành chính & Tài liệu
  contracts: {
    key: 'contracts',
    title: 'Hợp đồng',
    category: 'admin_docs',
    icon: 'FileText',
    color: '#2563EB',
    bgColor: '#EFF6FF',
    adminRoute: '/admin/contracts',
    leaderRoute: '/admin/contracts',
    employeeRoute: '/employee/contracts',
  },
  documents: {
    key: 'documents',
    title: 'Tài liệu nội bộ',
    category: 'admin_docs',
    icon: 'FolderOpen',
    color: '#D97706',
    bgColor: '#FEF3C7',
    adminRoute: '/admin/documents',
    leaderRoute: '/admin/documents',
    employeeRoute: '/employee/documents',
  },
  task_groups: {
    key: 'task_groups',
    title: 'Nhóm việc',
    category: 'admin_docs',
    icon: 'Layers',
    color: '#4F46E5',
    bgColor: '#EEF2FF',
    adminRoute: '/admin/task-groups',
    leaderRoute: '/leader/task-groups',
    employeeRoute: '/employee/tasks',
  },
  daily_reports: {
    key: 'daily_reports',
    title: 'Báo cáo ngày',
    category: 'admin_docs',
    icon: 'FileSpreadsheet',
    color: '#16A34A',
    bgColor: '#DCFCE7',
    adminRoute: '/admin/daily-reports',
    leaderRoute: '/leader/daily-reports',
    employeeRoute: '/employee/daily-reports',
  },
  news: {
    key: 'news',
    title: 'Đăng tin tức',
    category: 'admin_docs',
    icon: 'Newspaper',
    color: '#0D9488',
    bgColor: '#CCFBF1',
    adminRoute: '/admin/newsfeed',
    leaderRoute: '/leader/newsfeed',
    employeeRoute: '/employee/newsfeed',
  },

  // Tài chính & Đãi ngộ
  financial: {
    key: 'financial',
    title: 'Duyệt tài chính',
    category: 'finance',
    icon: 'Receipt',
    color: '#16A34A',
    bgColor: '#DCFCE7',
    adminRoute: '/leader/expenses',
    leaderRoute: '/leader/expenses',
    employeeRoute: '/employee/expenses',
  },
  payslip: {
    key: 'payslip',
    title: 'Bảng lương',
    category: 'finance',
    icon: 'CreditCard',
    color: '#2563EB',
    bgColor: '#EFF6FF',
    adminRoute: '/admin/payslip',
    leaderRoute: '/leader/payslip',
    employeeRoute: '/employee/payslip',
  },
  vault: {
    key: 'vault',
    title: 'Ví Thưởng Tết',
    category: 'finance',
    icon: 'Coins',
    color: '#F59E0B',
    bgColor: '#FEF3C7',
    adminRoute: '/admin/vault',
    leaderRoute: '/leader/vault',
    employeeRoute: '/employee/leveling',
    badgeKey: 'pendingVault',
  },
  levels: {
    key: 'levels',
    title: 'Cấu hình Level',
    category: 'finance',
    icon: 'Crown',
    color: '#D97706',
    bgColor: '#FEF3C7',
    adminRoute: '/admin/levels',
    leaderRoute: '/leader/leveling',
    employeeRoute: '/employee/leveling',
  },
  competition: {
    key: 'competition',
    title: 'Duyệt thi đua',
    category: 'finance',
    icon: 'Trophy',
    color: '#EAB308',
    bgColor: '#FEF9C3',
    adminRoute: '/admin/competition/review',
    leaderRoute: '/admin/competition/review',
    employeeRoute: '/employee/leveling',
  },

  // Kho bãi & Tài sản
  assets: {
    key: 'assets',
    title: 'Tài sản',
    category: 'warehouse',
    icon: 'Laptop',
    color: '#475569',
    bgColor: '#F1F5F9',
    adminRoute: '/admin/assets',
    leaderRoute: '/admin/assets',
    employeeRoute: '/employee/assets',
  },
  incidents: {
    key: 'incidents',
    title: 'Sự cố tài sản',
    category: 'warehouse',
    icon: 'AlertTriangle',
    color: '#EF4444',
    bgColor: '#FEE2E2',
    adminRoute: '/admin/asset-incidents',
    leaderRoute: '/admin/asset-incidents',
    employeeRoute: '/employee/assets',
  },
  warehouses: {
    key: 'warehouses',
    title: 'Kho bãi',
    category: 'warehouse',
    icon: 'Warehouse',
    color: '#B45309',
    bgColor: '#FEF3C7',
    adminRoute: '/admin/warehouses',
    leaderRoute: '/warehouse-manager',
    employeeRoute: '/warehouse-manager',
  },
  materials: {
    key: 'materials',
    title: 'Vật tư kho',
    category: 'warehouse',
    icon: 'Package',
    color: '#1E40AF',
    bgColor: '#DBEAFE',
    adminRoute: '/admin/materials',
    leaderRoute: '/admin/materials',
    employeeRoute: '/warehouse-manager',
  },
  stock_receipts: {
    key: 'stock_receipts',
    title: 'Nhập kho',
    category: 'warehouse',
    icon: 'Boxes',
    color: '#0F766E',
    bgColor: '#CCFBF1',
    adminRoute: '/admin/stock-receipts',
    leaderRoute: '/warehouse-manager/stock-receipts',
    employeeRoute: '/warehouse-manager/stock-receipts',
  },
  material_issues: {
    key: 'material_issues',
    title: 'Xuất kho',
    category: 'warehouse',
    icon: 'Boxes',
    color: '#C2410C',
    bgColor: '#FFEDD5',
    adminRoute: '/admin/material-issues',
    leaderRoute: '/warehouse-manager/material-issues',
    employeeRoute: '/warehouse-manager/material-issues',
  },
  inventory_checks: {
    key: 'inventory_checks',
    title: 'Kiểm kê kho',
    category: 'warehouse',
    icon: 'ClipboardCheck',
    color: '#6B21A8',
    bgColor: '#F3E8FF',
    adminRoute: '/admin/inventory-checks',
    leaderRoute: '/warehouse-manager/inventory-checks',
    employeeRoute: '/warehouse-manager/inventory-checks',
  },
  ai_chat: {
    key: 'ai_chat',
    title: 'Trợ lý AI',
    category: 'warehouse',
    icon: 'Zap',
    color: '#D97706',
    bgColor: '#FEF3C7',
    adminRoute: '/admin/ai-assistant',
    leaderRoute: '/admin/ai-assistant',
    employeeRoute: '/employee/ai-chat',
  },
};

export const ALL_APPS_LIST: AppRegistryItem[] = Object.values(APP_REGISTRY);

export function getAppRoute(item: AppRegistryItem, role: 'ADMIN' | 'LEADER' | 'EMPLOYEE' = 'ADMIN'): string {
  if (role === 'ADMIN') return item.adminRoute || item.leaderRoute || item.employeeRoute || '/admin/(tabs)';
  if (role === 'LEADER') return item.leaderRoute || item.employeeRoute || item.adminRoute || '/leader/(tabs)';
  return item.employeeRoute || item.leaderRoute || item.adminRoute || '/employee/(tabs)';
}
